version: "3.9"

services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - default

networks:
  default:
    external: true
    name: existing-network
