version: "3.9"

services:
  gateway:
    container_name: gateway
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:main
    environment:
      - ENV=${ENVIRONMENT}
      - STORAGE_PATH=${STORAGE_PATH}
      - TOKEN_TTL=${TOKEN_TTL}
      - PORT=${SERVER_PORT}
      - TIMEOUT=${TIMEOUT}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - default

networks:
  default:
    external: true
    name: existing-network

